### PR TITLE
Added logger for eauth roles

### PR DESCRIPTION
**Pull request by abdul-fs**
Addresses Issue # 1182

Describe the pull request here, including any supplemental information needed to understand it.
Pull request for Eauth Added log statement to capture approles from eauth in usda-eauth

## This pull request is ready to merge when...

- [ ] Tests have been updated 
- [ ] All tests are passing and meet coverage, linting, and accessibility requirements. And no security vulnerabilities ⚫️(Circle)
- [ ] This code has been reviewed by someone other than the original author

### CODE REVIEW

**Comment by briandavidson** [comment]
@abdul-fs I noticed this PR had been sitting for a bit, was just wondering if you were still using it?

**Comment by abdul-fs** [comment]
@briandavidson yup. there is still working going on. Sirisha is testing in dev to make sure eauth gets separated from whitelist. and we  will be pushing this to staging.

**Comment by briandavidson** [comment]
@abdul-fs there are a number of issues with this pull request:
- the code is doing much more than what the PR describes
- there is no connected issue
- this code is outdated at this point
- biggest issue: the source and destination branches are reversed

i recommend we just close this one out at this point, i don't think it's relevant any longer.

**Comment by briandavidson** [comment]
@abdul-fs this PR has been sitting here since February. Do you still need this or can we close it?

**Comment by abdul-fs** [comment]
> @abdul-fs this PR has been sitting here since February. Do you still need this or can we close it?

we should be good to close this. if you have her changes in your branch.

**Pull request closed without merging**
