### PR TITLE
Cookie session

### PR DESCRIPTION
**Pull request by mtlaney**
﻿## Summary
Addresses Issue #1418 

Please note if fully resolves the issue per the acceptance criteria: Yes

*Add cookies package which is a dependency of cookie-session*

## This pull request is ready to merge when...
- [x] Feature branch is starts with the issue number
- [ ] Is connected to its original issue via zenhub 👇
- [x] Tests have been updated 
- [x] All tests are passing and meet coverage, linting, and accessibility requirements. And no security vulnerabilities ⚫️(Jenkins)
- [x] This code has been reviewed by someone other than the original author

### CODE REVIEW

**Review by abdul-fs — APPROVED** [review]

**Review by mgwalker — APPROVED** [review]
Worth a shot!

**Comment by JonathanLerner54** [comment]
While reviewing the changes to the code to fix this issue while updating the SIA document,  I noted that the  "httpOnly: true," statement was dropped.  
**Was this intended?**
Won't this leave us vulnerable to Cross Site Scripting attacks?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by mgwalker** [comment]
Good catch! I saw it was the same number of properties and didn't even blink. You're right, that will create a XSS vulnerability.

**Comment by mtlaney** [comment]
@JonathanLerner54 @mgwalker httpOnly defaults to true with cookie-session.
[https://www.npmjs.com/package/cookie-session](https://www.npmjs.com/package/cookie-session)

**Comment by mgwalker** [comment]
While we're looking at `cookie-session` documentation, I want to point out [this bit](https://www.npmjs.com/package/cookie-session#cookie-options) because I'm still 95% sure that nesting the cookie configuration within a `cookie` properties is incorrect. `cookie-session` pulls out the options it knows how to handle and passes "other options" along to `cookies.set`. (You can also verify this by looking at [the cookie-session source](https://github.com/expressjs/cookie-session/blob/master/index.js#L41) where it parses the options, and you'll notice it doesn't use `.cookie` anywhere, it just passes the options right along. And if you then look at how [`cookie.set`](https://github.com/pillarjs/cookies/blob/master/index.js#L83) works, you'll see it similarly just passes options along (on line 88, the options get passed into the cookie constructor, and on line 133, each option gets assigned to the Cookie object).

So while this PR is worth a shot, I don't expect it'll resolve the `samesite` issue. I'm curious if the reason the tests started to fail in CI on the PR I opened is because suddenly the `secure` cookie option was being set to `true`, whereas it had previously not been set at all because the options weren't making their way to the actual cookie object.

**Comment by mtlaney** [comment]
@mgwalker you could very well be right. To be honest, the documentation on cookie-session is incredibly lacking. The nested cookie config was originally setup by 18f and always seemed to work. However when I strip the entire cookie nest it still works so it may not be doing anything. The reason I decided to keep it was I can find some stackoverflow examples where they nest the cookie options. 

If this truly doesn't do anything with the correct dependency, then we're back at the drawing board (try the not nested structure, re-write all of our cookies, or use express-session and re-work how all of our cookies work). I am by no means a cookie expert though, hence why I need some help here.

**Comment by mgwalker** [comment]
Agreed on the documentation! I've never used `cookie-session` before, but I have used the underlying `cookies` library directly. Handling the cookies yourself is not ideal, but it's also not super hard – you essentially end up having to hook the server's `writeHead` method and insert your cookies on the way out the door. But using a library purpose-built for it is obviously preferable.

**Comment by JonathanLerner54** [comment]
Thanks for the check on the httpOnly is on by default.  

SIA has been reviewed by Jon Lerner, SSA, and recommend release to production.  SIA and this issue card archived in Pinyon folder:   \Box\ePermits\SOP\ePermits Releases\FY20 ePermits Release to Production 1467

**Comment by mgwalker** [comment]
I'll write this up here and copy it over to the issue separately, if this PR doesn't fix the problem.

I've run the tests locally with the following set of session configurations:

### As-is

```js
app.use(
  session({
    name: 'session',
    keys: new Keygrip([vcapConstants.PERMIT_SECRET], 'sha256', 'base64'),
    maxAge: 3600000, // 1 hour
    cookie: {
      secure: true,
      httpOnly: true,
      domain
    }
  })
);
```

Result: 4 tests related to Christmas trees fail

### Un-nested

```js
app.use(
  session({
    name: 'session',
    keys: new Keygrip([vcapConstants.PERMIT_SECRET], 'sha256', 'base64'),
    maxAge: 3600000, // 1 hour
    secure: true,
    httpOnly: true,
    domain
  })
);
```

Result: 13 tests fail, including one that got a `401` status code when it expected a `404`. The extra tests failing suggests that either:
- the cookies were working fine with nested properties and un-nesting broke it
- the cookies were never working properly, and this particular set of options causes them to fail in testing

### Un-nested, without `secure` and `domain` configurations

```js
app.use(
  session({
    name: 'session',
    keys: new Keygrip([vcapConstants.PERMIT_SECRET], 'sha256', 'base64'),
    maxAge: 3600000, // 1 hour
    httpOnly: true,
  })
);
```

Result: The same tests that failed originally are now failing again. This suggests that the cookie options should be ***un-nested*** and that he `secure` and `domain` options are causing the tests to fail. This makes sense: the tests are probably not running over SSL, so cookies wouldn't be set, and `domain` is being derived from VCAP variables, which are not present in testing.

---

So I suspect we need to do two things:

1. Un-nest the cookie properties
2. Set `secure` and `domain` differently if `process.NODE_ENV` is equal to `test`
   - alternatively, setup SSL and a DNS name in testing, but that seems like a lot more effort

**Pull request merged**
