### PR TITLE
RELEASE 11-05-2019

### PR DESCRIPTION
**Pull request by abdul1234e**
﻿## Summary
Addresses Issue # 
#1007 
#1005 
#1008
#1010 
#1012 
#1013

## This pull request is ready to merge when...
- [x] Tests have been updated 
- [x] All tests are passing and meet coverage, linting, and accessibility requirements. And no security vulnerabilities ⚫️(Circle)
- [x] This code has been reviewed by someone other than the original author

### CODE REVIEW

**Comment by abdul1234e** [comment]
> This would be a merge to master and push to production. The pull request should be filled out and labeled as such.
> 
> See #1002
> 
> Will also need an SIA and approval from PO before we do a production push.

Updated. Sure will create SIA for jon blessing.

**Comment by JonathanLerner54** [comment]
Need someone to completed the This pull request is ready to merge when... section  PLEASE.

**Comment by JonathanLerner54** [comment]
I need someone to completed the "This pull request is ready to merge when..." section so I can completed the ISSO security review.  SIA is completed and on Pinyon.   THANKS

**Comment by abdul1234e** [comment]
> I need someone to completed the "This pull request is ready to merge when..." section so I can completed the ISSO security review. SIA is completed and on Pinyon. THANKS

Its done. It ready to merge the pull request tomorrow morning at 8:30am.

**Pull request merged**
