### PR TITLE
Revert "Delete-Package-lock.json"

### PR DESCRIPTION
**Pull request by abdul-fs**
Reverts USDAForestService/fs-open-forest-platform#1430

Addresses Issue # 1418

Please note if fully resolves the issue per the acceptance criteria: Y/N Y

Reverting back to good known state. 

This pull request is ready to merge when...
- [ ] Feature branch is starts with the issue number
- [x] Is connected to its original issue via zenhub 👇
- [x] Tests have been updated 
- [x] All tests are passing and meet coverage, linting, and accessibility requirements. And no security vulnerabilities ⚫️(Jenkins)
- [x] This code has been reviewed by someone other than the original author

### CODE REVIEW

**Review by mwreiss — APPROVED** [review]
Ready to go once SIA is completed.

**Comment by JonathanLerner54** [comment]
Approved for rollback to last known good approved release.  No risk

Reviewed by Jon Lerner, SSA for ePermits.

**Comment by JonathanLerner54** [comment]
SIA document has been archived in Pinyon Folder:  ePermits\SOP\ePermits Releases\FY20 ePermits Production Release  #1430

**Comment by JonathanLerner54** [comment]
Updated SIA reviewed and recommend release to production by Jon Lerner,  who performed security review of the changes and determined the risk is low.  These changes correct two errant characters: 
1. extraneous coma in the previous release that needed to be removed in the run sonarqube call 
 2. changed http to https for the The npm public registry call statement.  These two changes are low risk.

**Pull request merged**
